title: Major Set
url: https://majorset.be
gh_url: https://github.com/majorset/majorset.github.io/raw/master
collections:
  events:
    titles: Events
    output: false
  musicians:
    titles: Musicians
    output: false
future: true
plugins:
  - jekyll-sitemap
