title: Major Set
gh_url: https://github.com/majorset/majorset.github.io/raw/master
collections:
  events:
    titles: Events
    output: false
  musicians:
    titles: Musicians
    output: false
future: true
